apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: inventorybackend-development
  namespace: dp-default-inventory-development-95df624c
spec:
  parentRefs:
  - name: gateway-default
    namespace: openchoreo-data-plane
  hostnames:
  - "inventorybackend-development.openchoreoapis.localhost"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: inventorybackend
      port: 80
